name: ACR最终构建推送
on:
  push:
    branches: [ main ]
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 登录阿里云ACR
        run: docker login ${{ secrets.ALIYUN_REGISTRY }} -u ${{ secrets.ALIYUN_REGISTRY_USER }} -p ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: 构建镜像
        run: |
          IMAGE_REPO="${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/web"
          TAG="${{ github.sha }}"
          docker build -t "${IMAGE_REPO}:${TAG}" -t "${IMAGE_REPO}:latest" .

      - name: 推送镜像
        run: |
          IMAGE_REPO="${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/web"
          TAG="${{ github.sha }}"
          docker push "${IMAGE_REPO}:${TAG}"
          docker push "${IMAGE_REPO}:latest"

      - name: 退出登录
        run: docker logout ${{ secrets.ALIYUN_REGISTRY }}
